name: Question
description: Ask a question about any of ZVAR's software and data products.
title: "[Question] "
labels: question
assignees: []
body:
    - type: dropdown
      id: software
      attributes:
        label: Software
        description: Select the software this question is related to.
        options:
          - zvartools
          - Image difference forced photometry
          - fpw (python package)
          - fpw (GPU accelerated production pipeline)
          - Other (please specify)
    - type: textarea
      id: question
      attributes:
        label: Question
        description: Please provide a clear and concise description of your question.
    - type: textarea
      id: additional-context
      attributes:
        label: Additional context
        description: Add any other context or screenshots about the question here.  